import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3ContextProvider } from "@/contexts/ContextProvider";
import { SocketAuthProvider } from "@/contexts/SocketAuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3ContextProvider>
          {/* <SocketAuthProvider> */}
          {children}
          {/* </SocketAuthProvider> */}
        </Web3ContextProvider>
      </body>
    </html>
  );
}
